### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by chrabros** [joto/taginfo#187] opened 2016-09-15 06:15 UTC
Hi,
it seems that some strings are not in the translation file. I would like to translate them as well.

These are:

Main page: "This is the main taginfo site. It contains OSM data for the whole planet and is updated daily."

http://taginfo.openstreetmap.org/taginfo/translations - "Translations Overview" and "see texts"

http://taginfo.openstreetmap.org/reports/languages - "Native name", "English name", ...

http://taginfo.openstreetmap.org/about - "This is the main taginfo site. It contains OSM data for the whole planet and is updated daily.
This site is run by the OSMF and maintained by Jochen Topf and the Sysadmin team.
Several other taginfo sites are operated by different people for different areas of the world."

Would it be possible to add those in the translation file?
Thank you.

Best regards,
 Dalibor

**Comment by joto** [comment] 2016-09-15 07:28
Mostly duplicate of #172. http://taginfo.openstreetmap.org/taginfo/translations is a seldom used internal page, there is no translation necessary. http://taginfo.openstreetmap.org/reports/languages is translatable and you translated the texts.

**Closed** 2016-10-24 18:54 UTC
